# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)  # Tamaño de la ventana de login

        # Etiqueta y campo de texto para el Usuario
        self.label_usuario = QtWidgets.QLabel(Dialog)
        self.label_usuario.setGeometry(QtCore.QRect(100, 80, 55, 16))
        self.label_usuario.setObjectName("label_usuario")
        self.lineEdit_usuario = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_usuario.setGeometry(QtCore.QRect(170, 80, 150, 22))
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")

        # Etiqueta y campo de texto para la Contraseña
        self.label_contrasena = QtWidgets.QLabel(Dialog)
        self.label_contrasena.setGeometry(QtCore.QRect(100, 130, 55, 16))
        self.label_contrasena.setObjectName("label_contrasena")
        self.lineEdit_contrasena = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_contrasena.setGeometry(QtCore.QRect(170, 130, 150, 22))
        self.lineEdit_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)  # Contraseña oculta
        self.lineEdit_contrasena.setObjectName("lineEdit_contrasena")

        # Botón de inicio de sesión
        self.pushButton_login = QtWidgets.QPushButton(Dialog)
        self.pushButton_login.setGeometry(QtCore.QRect(150, 190, 100, 28))
        self.pushButton_login.setObjectName("pushButton_login")

        # Mensaje de error
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(100, 230, 200, 16))
        self.label_error.setStyleSheet("color: red;")
        self.label_error.setObjectName("label_error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.label_usuario.setText(_translate("Dialog", "Usuario:"))
        self.label_contrasena.setText(_translate("Dialog", "Contraseña:"))
        self.pushButton_login.setText(_translate("Dialog", "Iniciar sesión"))
        self.label_error.setText(_translate("Dialog", ""))  # Inicialmente sin mensaje de error
